# SVM on internet advertising data 

#from http://archive.ics.uci.edu/ml/machine-learning-databases/internet_ads/
#Based on a pluralsight tutorialabs

In [40]:
import numpy as np
import pandas as pd

datafile = "./ad.data"
data = pd.read_csv(datafile, sep=',', header=None, low_memory=False)
data.head(11)

{'ad.', 'nonad.'}

In [ ]:
#change missing values to NaN

In [17]:
data.isnull().values.any()

False

In [35]:
#replace all the empty cells with na
def toNum(cell):
    try:
        return np.float(cell)
    except:
        return np.nan

def seriestoNum(series):
    return series.apply(toNum)

train_data = data.iloc[0:, 0:-1].apply(seriestoNum)
train_data.head(11)

,0,1,2,3,4,5,6,7,8,9,...,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557
0,125.0,125.0,1.0000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,57.0,468.0,8.2105,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,33.0,230.0,6.9696,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,59.0,460.0,7.7966,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,60.0,234.0,3.9000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
train_data = train_data.dropna()
train_data.head(11)

,0,1,2,3,4,5,6,7,8,9,...,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557
0,125.0,125.0,1.0000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,57.0,468.0,8.2105,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,33.0,230.0,6.9696,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,59.0,460.0,7.7966,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,60.0,234.0,3.9000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,60.0,468.0,7.8000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,90.0,52.0,0.5777,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
#Label data

In [67]:
notad, ad = tuple(set(data.iloc[:, -1]))

def label(output):
    if (output == ad):
        return 1
    else:
        return 0
    
train_labels = data.iloc[train_data.index, -1].apply(label)

In [ ]:
#Train the model with Linear SVC

In [68]:
from sklearn.svm import LinearSVC

clf = LinearSVC()
clf.fit(train_data[100:2300], train_labels[100:2300])

/Users/mpraveen/anaconda3/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [69]:
#Test the data

In [111]:
def predictedValue(cell):
    return clf.predict(cell.values.reshape(1, -1))
predicted_values = train_data.apply(predictedValue, axis=1)

In [129]:
true_positives = 0
false_positives = 0
true_negetives = 0
false_negetives = 0

for predicted, actual in zip(predicted_values, train_labels):
    if (predicted[0] == actual == 1):
        true_positives += 1
    elif (predicted[0] == actual == 0):
        true_negetives += 1
    elif (predicted[0] == 1 and predicted[0] != actual):
        false_positives += 1
    else:
        false_negetives += 1
        
print("true_positives   =", true_positives)
print("false_positives  =", false_positives)
print("true_negetives   =", true_negetives)
print("false_negetives  =", false_negetives)

true_positives   = 298
false_positives  = 5
true_negetives   = 1973
false_negetives  = 83

In [133]:
precision = true_positives / ( true_positives + false_positives)
recall = true_positives/(true_positives + false_negetives)
accuracy= 2*precision*recall/(precision + recall)

print("precision  =", precision)
print("recall     =", recall)
print("accuracy   =", recall)

precision  = 0.9834983498349835
recall     = 0.7821522309711286
accuracy   = 0.7821522309711286